#!/usr/bin/env python3
"""
Generate js/font_atlas.js — the real glyph atlas consumed by webgpu.html.

Mirrors font_atlas_packager/src/main.rs exactly (same FNV-1a mixing, same
4x6 packing) so the JS engine and the Rust crate produce identical signatures.
Round 2 swaps the simulated coverage for real ttf-parser ray casts on the
Rust side; the JS stays a faithful mirror until then (R: doc-faithful sims).
"""
import json
import os

SUBPIXEL_SEED = 0x75F652
COLS = 4
ROWS = 6

GLYPHS = list(" .:-=+*#%@█") + list("abcdefghijklmnopqrstuvwxyz") + \
         list("ABCDEFGHIJKLMNOPQRSTUVWXYZ") + list("0123456789")


def fnv_mix(g, c, r):
    h = 0x811C9DC5
    h = ((h ^ g) * 0x01000193) & 0xFFFFFFFF
    h = ((h ^ c) * 0x01000193) & 0xFFFFFFFF
    h = ((h ^ r) * 0x01000193) & 0xFFFFFFFF
    return h


def simulate_outline_intersection(glyph_index, col, row):
    return fnv_mix(glyph_index, col, row) % 100 < 45


def pack_to_u32(glyph_index):
    bits = 0
    for row in range(ROWS):
        for col in range(COLS):
            if simulate_outline_intersection(glyph_index, col, row):
                bits |= 1 << (row * COLS + col)
    return bits


def main():
    atlas = [pack_to_u32(i) for i in range(len(GLYPHS))]
    unique = len(set(atlas))
    total_bits = len(atlas) * COLS * ROWS
    set_bits = sum(bin(s).count("1") for s in atlas)

    js = "// Auto-generated by tools/gen_atlas.py — mirrors font_atlas_packager.\n"
    js += f"// glyphs: {len(GLYPHS)}, unique signatures: {unique}, "
    js += f"coverage: {100.0*set_bits/total_bits:.1f}%\n"
    js += f"const FONT_ATLAS_DATA = new Uint32Array({json.dumps(atlas)});\n"
    js += f"const FONT_ATLAS_GLYPHS = {json.dumps(''.join(GLYPHS))};\n"

    out = os.path.join(os.path.dirname(__file__), "..", "js", "font_atlas.js")
    with open(out, "w") as f:
        f.write(js)

    print(f"atlas: {len(atlas)} glyphs, {unique} unique, "
          f"{100.0*set_bits/total_bits:.1f}% coverage, "
          f"{len(atlas)*4} bytes → js/font_atlas.js")


if __name__ == "__main__":
    main()
